### ISSUE TITLE
Increase upload size limit

### ISSUE THREAD

**Issue by markfijneman** [JJ-8/CTFNote#97]
The current limit (1MB, which is the default value of nginx) is not enough for a lot of screenshots taken on screens with high resolutions. Attempting to upload a screenshot bigger than 1MB results in the following error from `/pad/uploadimage`: "413 Request Entity Too Large - nginx". Currently I would have to modify the image trough an external editor to make it smaller, which is not really preferable during a CTF where you have limited time to solve challenges.

I think increasing the limit to 5MB would alleviate this problem in most cases. The following change to `/front/nginx.conf` resolved the problem on my own instance:
```diff
diff --git a/nginx.conf b/nginx-2.conf
index 552f448..5a177c7 100644
--- a/nginx.conf
+++ b/nginx-2.conf
@@ -62,5 +62,6 @@ server {
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         add_header Pragma "no-cache";
+        client_max_body_size 5M;
     }
 }
```

**Comment by JJ-8** [comment]
The outer-nginx config should also be updated, right? So the nginx version that is served on the host with the configuration described in the README.

**Comment by markfijneman** [comment]
On my instance changing the inner-nginx config was enough, but that might only work with my specific setup. Could you test it yourself to see what happens?

**Comment by JJ-8** [comment]
I think it won't hurt to increase the `client_max_body_size` value by default. Testing on production it is a bit difficult without a ghcr container (and locally I don't have an outer-nginx enabled). I think we just should open a PR to update the inner and outer nginx config to set these values to `5M`.
